//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorieVehicule
    {
        public CategorieVehicule()
        {
            this.Vehicules = new HashSet<Vehicule>();
        }
    
        public int IdCategorie { get; set; }
        public string NomCategorie { get; set; }
    
        public virtual ICollection<Vehicule> Vehicules { get; set; }
    }
}
