//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Commentaires = new HashSet<Commentaire>();
            this.Favoris = new HashSet<Favori>();
            this.TypeComptesClients = new HashSet<TypeComptesClient>();
            this.Ventes = new HashSet<Vente>();
        }
    
        public int IdClient { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Courriel { get; set; }
        public string Telephone { get; set; }
        public string NumeroCivique { get; set; }
        public string Rue { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CodePostal { get; set; }
        public string NumeroPermis { get; set; }
        public bool Sexe { get; set; }
        public string Photo { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual ICollection<Commentaire> Commentaires { get; set; }
        public virtual ICollection<Favori> Favoris { get; set; }
        public virtual ICollection<TypeComptesClient> TypeComptesClients { get; set; }
        public virtual ICollection<Vente> Ventes { get; set; }
    }
}
