//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int IdCommentaire { get; set; }
        public int IdVehicule { get; set; }
        public int IdClient { get; set; }
        public Nullable<System.DateTime> DateCommentaire { get; set; }
        public Nullable<int> Cote { get; set; }
        public string Commentaire1 { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
