//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbConcessionnaireEntities : DbContext
    {
        public DbConcessionnaireEntities()
            : base("name=DbConcessionnaireEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorieVehicule> CategorieVehicules { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Commentaire> Commentaires { get; set; }
        public virtual DbSet<Favori> Favoris { get; set; }
        public virtual DbSet<Paiement> Paiements { get; set; }
        public virtual DbSet<TypeCompte> TypeComptes { get; set; }
        public virtual DbSet<TypeComptesClient> TypeComptesClients { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
        public virtual DbSet<Vente> Ventes { get; set; }
    }
}
