//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeComptesClient
    {
        public int IdCompte { get; set; }
        public int IdClient { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
    
        public virtual TypeCompte TypeCompte { get; set; }
        public virtual Client Client { get; set; }
    }
}
