//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCompte
    {
        public int IdCompte { get; set; }
        public string TypeCompte1 { get; set; }
    
        public virtual TypeComptesClient TypeComptesClient { get; set; }
    }
}
