//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public Vehicule()
        {
            this.Commentaires = new HashSet<Commentaire>();
            this.Favoris = new HashSet<Favori>();
            this.Ventes = new HashSet<Vente>();
        }
    
        public int IdVehicule { get; set; }
        public string Marque { get; set; }
        public int VitesseTerre { get; set; }
        public int VitesseEau { get; set; }
        public string DescriptionVehicule { get; set; }
        public string Apparition { get; set; }
        public string Fabricant { get; set; }
        public string Moteur { get; set; }
        public decimal PrixVente { get; set; }
        public decimal PrixAchat { get; set; }
        public string Photo { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
        public string Photo4 { get; set; }
        public int QuantiteInventaire { get; set; }
        public int IdCategorie { get; set; }
    
        public virtual CategorieVehicule CategorieVehicule { get; set; }
        public virtual ICollection<Commentaire> Commentaires { get; set; }
        public virtual ICollection<Favori> Favoris { get; set; }
        public virtual ICollection<Vente> Ventes { get; set; }
    }
}
