//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        public Vente()
        {
            this.Paiements = new HashSet<Paiement>();
        }
    
        public int IdVente { get; set; }
        public int IdVehicule { get; set; }
        public int IdClient { get; set; }
        public Nullable<System.DateTime> DateVente { get; set; }
        public decimal PrixVente { get; set; }
        public int Quantite { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Paiement> Paiements { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
