//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        public Vente()
        {
            this.Paiements = new HashSet<Paiement>();
        }
    
        public int IdVente { get; set; }
        public int IdVehicule { get; set; }
        public int IdClient { get; set; }
        public Nullable<System.DateTime> DateVente { get; set; }
        public decimal PrixVente { get; set; }
        public int Quantite { get; set; }
    
        public virtual Vehicule Vehicule { get; set; }
        public virtual ICollection<Paiement> Paiements { get; set; }
        public virtual Client Client { get; set; }
    }
}
